### ISSUE TITLE
März Meetup bei Ambient Innovation

### ISSUE THREAD

**Issue by jhilden** [reactcologne/meetups_orga#1]
Requirements:
* Platz für 20-50 Teilnehmer (durchschnittlicch ca. 35)
* Räume für 2 parallele Tracks + ggf. noch Platz für einen Social-/Hallway-Track
* Location sollte von innerhalb Köln OK erreichbar sein

Vorbereitung:
* [x] Datum in Slack vorschlagen und mindestens 24h auf Feedback warten
* [x] Co-Organisator bei Meetup.com werden
* [x] Event bei Meetup.com anlegen
* [x] Event über Meetup.com ankündigen
* [x] Event ggf. noch über andere Kanäle (z.B. Twitter) ankündigen
* [x] Moderator (ggf. Co-Moderator) festlegen
* [x] Getränke (und gerne auch Catering) organisieren

Am Tag des Events:
* [x] Schilder aufhängen (Eingangstür, Aufzug, usw.), damit die die Teilnehmer die richtigen Räumlichkeiten finden
* [x] Getränke kalt stellen

Standardablauf:

| Zeit     | Agendapunkt |
| -------- | ----------- |
| ab 18:30 | Ankommen
| 19:00    | Welcome, Unternehmensvorstellung, Sessionplanung (Pitches)
| 19:30-20:20 | Sessions Slot 1
| 20:20 | kurze Pause
| 20:30-21:20 | Sessions Slot 2

Dieses Issue kann dazu dienen ggf. Themen vorzubereiten und weitere Orga-Dinge zu besprechen

**Comment by felixschul** [comment]
Danke @jhilden 

wie ist denn das Slack-Team, das dazu gegründet werden sollte? Danke dir und viele Grüße Felix

**Comment by jhilden** [comment]
@felixschul hier kannst dir einen Invite zuschicken lassen: https://reactcologne-slack.herokuapp.com/

**Comment by jhilden** [comment]
Sofern ich in der Woche nicht beim Skifahren bin (http://hackberg.hack.institute/ wird ggf. auf die Woche verschoben), würde ich meinen Talk "Living-Styleguide-Driven Development with storybook", für den beim Barcamp kein Slot mehr war, für das März Meetup vorbereiten.

**Comment by jhilden** [comment]
@felixschul ich hab dich auf Meetup.com zum "Event-Organisator" gemacht, damit müsstest du jetzt die nötigen Rechte haben um das Event für März dort anzulegen und anzukündigen.

Es wäre wahrscheinlich gut, wenn wir die einzelnen Schritte ein bisschen mitschreiben, um es zukünftigen Hosts noch einfacher zu machen.

Ausserdem, sofern ich am 12.3. nicht beim Skifahren bin (http://hackberg.hack.institute/ wird ggf. auf die Woche verschoben), würde ich meinen Talk "Living-Styleguide-Driven Development with Storybook", für den beim Barcamp kein Slot mehr war, für das März Meetup vorbereiten.

**Comment by felixschul** [comment]
Super, danke. Das hat geklappt. Ich stelle das Event dann ein. Falls es etwas zu dokumentieren gibt, mache ich das. Ich kann allerdings leider nicht die Beschreibung der eigentlichen Gruppe ändern, sie ist noch sehr auf React Native fokussiert ("App developers tired of three incompatible tech stacks for writing web and mobile apps."). Ich denke dafür brauchen wir Julia.

**Comment by jhilden** [comment]
@felixschul wie hat die Meetup-Orga geklappt letzte Woche?  Irgendwelche zusätzlichen Infos, die vielleicht für zukünftiges Hosts relevant sein könnten?

Ansonsten schließe ich das Issue mal.

**Comment by jhilden** [comment]
Sorry, bin gerade ausm Urlaub zurück gekommen und hab mich total vertan beim Datum :blush:  Igoniertiert mich bitte :)

**Comment by felixschul** [comment]
Die Moderation wird Jan Bürling übernehmen :)
