### ISSUE TITLE
Dezember Meetup Glühwein Edition

### ISSUE THREAD

**Issue by timomeh** [reactcologne/meetups_orga#10]
2 Möglichkeiten:
* Wir treffen uns auf einem Weihnachtsmarkt
* Eine Firma hostet uns weihnachtlich

Zum Ende des Jahres würde ich vorschlagen nicht unser klassisches Meetup-Format mit Talks zu machen, sondern einfach ein nettes Beisammensein. Das kommt bei anderen Meetups auch immer gut an.

--- 

Requirements:
* Platz für 20-50 Teilnehmer (durchschnittlich ca. 35)
* Räume für 2 parallele Tracks + ggf. noch Platz für einen Social-/Hallway-Track
* Location sollte von innerhalb Köln OK erreichbar sein

Vorbereitung:
* [ ] Datum in Slack #orga vorschlagen und mindestens 24h auf Feedback warten (z.B. ob es schwerwiegende Terminkonflikte mit anderen Events oder so gibt)
* [ ] Co-Organisator bei Meetup.com werden
* [ ] Event bei Meetup.com anlegen
* [ ] Event über Meetup.com ankündigen
* [ ] Event ggf. noch über andere Kanäle (z.B. Twitter) ankündigen
* [ ] Ein paar Tage vor dem Event Reminder mit Last-Minute Infos verschicken ((ventseite > Organistoren Tools > Teilnehmer kontaktieren)
* [ ] Moderator (ggf. Co-Moderator) festlegen
* [ ] Getränke (und gerne auch Catering) organisieren

Am Tag des Events:
* [ ] Schilder aufhängen (Eingangstür, Aufzug, usw.), damit die Teilnehmer die richtigen Räumlichkeiten finden
* [ ] Getränke kalt stellen
* [ ] WiFI einrichten (ggf Passwort ändern) und Schilder aufhängen

Standardablauf:

| Zeit     | Agendapunkt |
| -------- | ----------- |
| ab 18:30 | Ankommen
| 19:00    | Welcome, Unternehmensvorstellung, Sessionplanung (Pitches)
| 19:30-20:20 | Sessions Slot 1
| 20:20 | kurze Pause
| 20:30-21:20 | Sessions Slot 2

**Comment by DanielaValero** [comment]
Hello, could it be an option to do half and half? 
I mean: Do the first sessions and instead of doing the second sessions at 20:30, going to a Christmas Market.

We could host (Publicis Sapient) the event, and it's 5min walk to the Christmas Market in Stadtgarten.
