### ISSUE TITLE
March meetup at KalkSpace hosted by Railslove

### ISSUE THREAD

**Issue by jhilden** [reactcologne/meetups_orga#12]
*Requirements*

- Space for 20-50 participants (usually average 35).
- Room for 2 parallel tracks, and maybe a social-/hallway-track.
- Your location should be accessible from central Cologne with public transport.
- Wi-Fi for participants.

*Preparation*

- [x] Suggest a date in Slack (#orga) and wait at least 24 hours for feedback (to check if it conflicts with other events)
- [x] Ask to be a co-organisator on meetup.com
- [x] Fill out the event infos on meetup.com
- [ ] Announce the event using meetup.com a few weeks before
- [ ] Announce and promote the event via Social Media
- [ ] Organize drinks (softdrinks & beer) and catering (snacks)
- [ ] A few days before the event: send a reminder through meetup.com with some last minute informations. (See [reminder_template.md](https://github.com/reactcologne/meetups_orga/blob/master/reminder_template.md))
- [ ] Check who will moderate the event

*At the day of the event*

- [ ] Put up sings outside and inside so participants know where to find your location
- [ ] Put up signs for Wi-Fi (SSID and Password)
- [ ] Fill up the fridge with your drinks

*Schedule*

| Time     |  |
| -------- | ----------- |
| from 18:30 | Arrival, Drinks, Socializing
| 19:00    | Welcome, Introducing the Host, Session Planning
| 19:30 - 20:20 | Sessions
| 20:20 | Break
| 20:30-21:20 | Sessions

*After the event*

- Thanks for being a host!
- If you need a list of participants for catering, you can download it from the meetup.com event page.
- Close this issue.

**Comment by jhilden** [comment]
cc @christinegotth

**Comment by timomeh** [comment]
Will be remote due to the current situation, thus I'm going to close this. We will host it at another time.
