### ISSUE TITLE
Meetup Account übernehmen

### ISSUE THREAD

**Issue by jhilden** [reactcologne/meetups_orga#2]
Zurzeit wird dem Meetup.com Account von Julia Müller von SilverTours (billiger-mietwagen) verwaltet und bezahlt. Da SilverTours aktuell nicht mehr so besonders aktiv am Meetup mitwirkt, sollte man das vielleicht mal übernehmen.

**Comment by jhilden** [comment]
Ich hab gerade herausgefunden, dass ich als "Co-Organisator" in der Mitgliederverwaltung auch andere zu "Event-Organisatoren" oder "Co-Organisatoren" machen kann. Vielleicht ist die Übernahme des Accounts also doch nicht so wichtig.

**Comment by jhilden** [comment]
Ein Problem ist auf jeden Fall, dass Julia auf Meetup als "Organisator" steht, aber anscheinend nicht auf Nachrichten reagiert.  Das wäre schlecht wenn uns jemand versucht auf diesem Wege zu kontaktieren.

**Comment by C3-TKO** [comment]
Welcher Account soll denn der neue Hauptorga posten sein? Ich werde das dann an Julia weiterleiten

**Comment by timomeh** [comment]
Done, wurde an mich übertragen. 🚀
