### ISSUE TITLE
Ende April Meetup bei Fond Of

### ISSUE THREAD

**Issue by jhilden** [reactcologne/meetups_orga#3]
Requirements:
* Platz für 20-50 Teilnehmer (durchschnittlicch ca. 35)
* Räume für 2 parallele Tracks + ggf. noch Platz für einen Social-/Hallway-Track
* Location sollte von innerhalb Köln OK erreichbar sein

Vorbereitung:
* [x] Datum in Slack vorschlagen und mindestens 24h auf Feedback warten
* [x] Co-Organisator bei Meetup.com werden
* [x] Event bei Meetup.com anlegen
* [x] Event über Meetup.com ankündigen
* [ ] Event ggf. noch über andere Kanäle (z.B. Twitter) ankündigen
* [x] Moderator (ggf. Co-Moderator) festlegen
* [x] Getränke (und gerne auch Catering) organisieren

Am Tag des Events:
* [ ] Schilder aufhängen (Eingangstür, Aufzug, usw.), damit die die Teilnehmer die richtigen Räumlichkeiten finden
* [ ] Getränke kalt stellen

Standardablauf:

| Zeit     | Agendapunkt |
| -------- | ----------- |
| ab 18:30 | Ankommen
| 19:00    | Welcome, Unternehmensvorstellung, Sessionplanung (Pitches)
| 19:30-20:20 | Sessions Slot 1
| 20:20 | kurze Pause
| 20:30-21:20 | Sessions Slot 2

**Comment by jhilden** [comment]
@brumm gibt es schon einen Termin?

**Comment by brumm** [comment]
Höchstwahrscheinlich der 25.04.

**Comment by brumm** [comment]
Ich kümmere mich heute mal um den internen Kram zum anmelden des Events 👍

**Comment by jhilden** [comment]
Steht das Datum jetzt für das Meetup?  Ist der 25.4. hier https://www.meetup.com/de-DE/React-Cologne/events/259756860/ korrekt?

Braucht ihr noch irgengdwas um das zu publishen/anzukündigen?

**Comment by brumm** [comment]
Datum steht und event ist gepublished ✅

**Comment by jhilden** [comment]
@brumm habt irgendwelches Orga-Feedback für zukünftige Hosts?
