### ISSUE TITLE
Mitte Juli bei AmbientInnovation

### ISSUE THREAD

**Issue by felixschul** [reactcologne/meetups_orga#5]
Requirements:
* Platz für 20-50 Teilnehmer (durchschnittlich ca. 35)
* Räume für 2 parallele Tracks + ggf. noch Platz für einen Social-/Hallway-Track
* Location sollte von innerhalb Köln OK erreichbar sein

Vorbereitung:
* [x] Datum in Slack #orga vorschlagen und mindestens 24h auf Feedback warten
* [x] Co-Organisator bei Meetup.com werden
* [x] Event bei Meetup.com anlegen
* [x] Event über Meetup.com ankündigen
* [x] Event ggf. noch über andere Kanäle (z.B. Twitter) ankündigen
* [x] Moderator (ggf. Co-Moderator) festlegen
* [x] Getränke (und gerne auch Catering) organisieren

Am Tag des Events:
* [x] Schilder aufhängen (Eingangstür, Aufzug, usw.), damit die Teilnehmer die richtigen Räumlichkeiten finden
* [x] Getränke kalt stellen
* [x] WiFI einrichten (ggf Passwort ändern) und Schilder aufhängen

Standardablauf:

| Zeit     | Agendapunkt |
| -------- | ----------- |
| ab 18:30 | Ankommen
| 19:00    | Welcome, Unternehmensvorstellung, Sessionplanung (Pitches)
| 19:30-20:20 | Sessions Slot 1
| 20:20 | kurze Pause
| 20:30-21:20 | Sessions Slot 2

**Comment by jhilden** [comment]
Ich hatte eigentlich mit @haynzz darüber gredet, dass SoundReply interessiert war uns im Juli zu hosten.  Leider aber immer noch ohne Bestätigung oder konkretem Terminvorschlag.

Wenn das klappen würde, wäre das schon cool, weil wir dann mehr Location kennenlernen.  Falls das aber jetzt nicht klappt (wegen fehlender Rückmeldung) würdet ihr dann immer noch als Host im Juli zur Verfügung stehen @felixschul?  (Ich frage erstmal nur provisorisch)

Als Datum war ein Wochentag in der Woche vom 15.7. vorgesehen.

**Comment by felixschul** [comment]
Hi @jhilden,

Sehr gerne. In der Woche wäre auch kein Problem. 

LG 
Felix

**Comment by jhilden** [comment]
Da ich von @haynzz nix mehr gehört habe, würde ich sagen lass uns das mal festmachen bei euch (AmbientInnovation). @felixschul magst du einen Tag vorschlagen in der Woche vom 15.7.?

**Comment by felixschul** [comment]
Sehr gerne! Mir würde es passen am
- Montag 15.7. 
- Mittwoch 17.7. 
- Donnerstag 18.7.

Ich sehe auf Anhieb keine relevanten anderen Meetups an einem der Tage: https://www.meetup.com/de-DE/find/events/?allMeetups=true&radius=31&userFreeform=Cologne%2C+Deutschland&mcId=z2829518&mcName=Cologne%2C+DE&month=7&day=15&year=2019&eventFilter=mysugg

Gibt es aus eurer Sicht bessere und schlechtere Tage? Falls alle gleich sind und ihr könnt, würde ich den 17.7. nehmen, weil das ein schönes rundes Datum ist und sich Mittwoch gut anfühlt :)

**Comment by jhilden** [comment]
:+1: für 17.7.

**Comment by ffgregormueller** [comment]
Kann in der Woche leider gar nicht (Geburt), deswegen halte ich mich raus. 😉

**Comment by felixschul** [comment]
Hi @ffgregormueller,

dann alles Gute für euch und eine schöne Zeit schonmal mit dem Baby :) 

Wenn ich nichts mehr höre, stelle ich das Meetup für den 17.7. ein.
