### ISSUE TITLE
August Meetup im Startplatz gehosted von Neoalto

### ISSUE THREAD

**Issue by jhilden** [reactcologne/meetups_orga#7]
Requirements:
* Platz für 20-50 Teilnehmer (durchschnittlich ca. 40)
* Räume für 2 parallele Tracks + ggf. noch Platz für einen Social-/Hallway-Track
* Location sollte von innerhalb Köln OK erreichbar sein

Vorbereitung:
* [x] Datum in Slack #orga vorschlagen und mindestens 24h auf Feedback warten
* [x] Co-Organisator bei Meetup.com werden
* [x] Event bei Meetup.com anlegen
* [x] Event über Meetup.com ankündigen
* [x] Event ggf. noch über andere Kanäle (z.B. Twitter) ankündigen
* [x] Moderator (ggf. Co-Moderator) festlegen
* [x] Getränke (und gerne auch Catering) organisieren

Am Tag des Events:
* [x] Schilder aufhängen (Eingangstür, Aufzug, usw.), damit die Teilnehmer die richtigen Räumlichkeiten finden
* [x] Getränke kalt stellen
* [x] WiFI einrichten (ggf Passwort ändern) und Schilder aufhängen

Standardablauf:

| Zeit     | Agendapunkt |
| -------- | ----------- |
| ab 18:30 | Ankommen
| 19:00    | Welcome, Unternehmensvorstellung, Sessionplanung (Pitches)
| 19:30-20:20 | Sessions Slot 1
| 20:20 | kurze Pause
| 20:30-21:20 | Sessions Slot 2

**Comment by jhilden** [comment]
@murraybo wir haben immer noch keinen Terminvorschlag von euch bekommen.  Könntest du dich da bitte drum kümmern, dass wir den Termin vor dem nächsten Meetup (nächste Woche am 6.6.) fest haben?

**Comment by murraybo** [comment]
21.8. ist jetzt reserviert

**Comment by timomeh** [comment]
https://www.meetup.com/de-DE/React-Cologne/events/261999685/

**Comment by murraybo** [comment]
Moderation würde ich übernehmen. Möchte noch einer aus der Stammorga Co-Moderieren ?

**Comment by felixschul** [comment]
Hallo @murraybo,

ich habe gerade gesehen, dass in dem Text auf meetup.com noch ein kleiner Fehler ist. 

> On August 21st we will have our 9th Meetup 

Es wird ja das 10. Meetup sein und hat auch den Titel #10.

Viele Grüße
Felix

**Comment by timomeh** [comment]
Da bin ich dran mit schuld, hab in den Titel zuerst #9 geschrieben 🙈

**Comment by timomeh** [comment]
Ich hab das mal gefixt

**Comment by timomeh** [comment]
@murraybo Schreibst du noch eine kurze Erinnerungs-Rundmail für das Meetup morgen? Wenn ja wär's super wenn du da erwähnen könntest, dass wir im Meetup ein kostenloses Ticket für den React Day Berlin (https://reactday.berlin/) verlosen.

**Comment by murraybo** [comment]
Am Dienstag im laufe des Tages. Das Meeting ist ja am Mittwoch. Ich habe jetzt mal ein Limit von 55 Gästen gesetzt. Mal sehen. Wie viele no shows haben wir so im Schnitt?

**Comment by timomeh** [comment]
No show rate ist bei 30% - 50%.

**Comment by timomeh** [comment]
Ach, ja, nicht für das Meetup morgen :D Ich hab kurz in der Zukunft gelebt
