### ISSUE TITLE
Oktober Meetup beim WDR

### ISSUE THREAD

**Issue by jhilden** [reactcologne/meetups_orga#9]
Requirements:
* Platz für 20-50 Teilnehmer (durchschnittlich ca. 35)
* Räume für 2 parallele Tracks + ggf. noch Platz für einen Social-/Hallway-Track
* Location sollte von innerhalb Köln OK erreichbar sein

Vorbereitung:
* [ ] Datum in Slack #orga vorschlagen und mindestens 24h auf Feedback warten (z.B. ob es schwerwiegende Terminkonflikte mit anderen Events oder so gibt)
* [ ] Co-Organisator bei Meetup.com werden
* [ ] Event bei Meetup.com anlegen
* [ ] Event über Meetup.com ankündigen
* [ ] Event ggf. noch über andere Kanäle (z.B. Twitter) ankündigen
* [ ] Ein paar Tage vor dem Event Reminder mit Last-Minute Infos verschicken ((ventseite > Organistoren Tools > Teilnehmer kontaktieren)
* [ ] Moderator (ggf. Co-Moderator) festlegen
* [ ] Getränke (und gerne auch Catering) organisieren

Am Tag des Events:
* [ ] Schilder aufhängen (Eingangstür, Aufzug, usw.), damit die Teilnehmer die richtigen Räumlichkeiten finden
* [ ] Getränke kalt stellen
* [ ] WiFI einrichten (ggf Passwort ändern) und Schilder aufhängen

Standardablauf:

| Zeit     | Agendapunkt |
| -------- | ----------- |
| ab 18:30 | Ankommen
| 19:00    | Welcome, Unternehmensvorstellung, Sessionplanung (Pitches)
| 19:30-20:20 | Sessions Slot 1
| 20:20 | kurze Pause
| 20:30-21:20 | Sessions Slot 2

**Comment by timomeh** [comment]
Termin: 9. Oktober
